### ISSUE TITLE
is.closed invalid count

### ISSUE THREAD

**Issue by clcazer** [mhahsler/arules#52]
when applying is.closed to an itemset class, sometimes I will get an error of "invalid count". This seems to occur only when the itemset has a support count of 1 but it does not occur with every itemset with a support count of 1. I'm trying to find why this occurs.

**Comment by mhahsler** [comment]
Please send me code and data to reproduce the problem.

**Comment by clcazer** [comment]
[is closed bug.xlsx](https://github.com/mhahsler/arules/files/3238684/is.closed.bug.xlsx)
require(dplyr)
require(xlsx)

#read data
data <- read.xlsx("data/is closed bug.xlsx", sheetIndex = 1)

#divide dataset by category
Cat1 <- filter(data, cat=="A") %>% select(-cat)
Cat2 <- filter(data, cat=="C") %>% select(-cat)

#create transactions
trans1 <- as(Cat1, "transactions")
trans2 <- as(Cat2, "transactions")

#mine sets
sets1 <- apriori(trans1, parameter=list(support=1/length(trans1),  
                                      maxlen=4, 
                                      minlen=2, 
                                      target="frequent itemsets"))

sets2 <- apriori(trans2, parameter=list(support=1/length(trans2),  
                                        maxlen=4, 
                                        minlen=2, 
                                        target="frequent itemsets"))

inspect(sets1)
inspect(sets2)
#some sets are contained in both with count==1

is.closed(sets1) #no problems
is.closed(sets2) #invalid count error

#invalid count error occurs when count==1 in sets2 but not in sets1
is.closed(sets2[1])
is.closed(sets1[1])

**Comment by mhahsler** [comment]
Thank you for your example. I have fixed the rounding bug in the support count calculation. A fixed version is on GitHub. The bug fix will be part of the next CRAN release.

**Comment by clcazer** [comment]
Sorry but I still get the same error after downloading from github
install.packages("~/arules-master.zip", repos = NULL, type = "win.binary")

**Comment by mhahsler** [comment]
It probably takes a whole to rebuild.
